name: Run Tests
on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: Install
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Test
        run: yarn turbo run test lint test:cypress
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: mattpocock
          TURBO_REMOTE_ONLY: "true"
